# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Daicon_watchos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Daicon_watchos

end

target 'Daicon_watchos WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Daicon_watchos WatchKit App

end

target 'Daicon_watchos WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Daicon_watchos WatchKit Extension
  pod 'Alamofire'

end
